config/routes.rb
Rails.application.routes.draw do
  root 'site_maps#new'

  resource :site_map, only: [:new, :create, :show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_maps_controller.rb
class SiteMapsController < ApplicationController
  def new
  end

  def create
    site_map = SiteMap.new(params[:site_map][:uri], 3)
    site_map.parse
    @file_path = site_map.to_file
    render :show
  rescue SocketError => e
    flash[:alert] = 'Site not available'
    redirect_to root_path
  rescue URI::InvalidURIError, SiteMap::Link::ParseError => e
    flash[:alert] = 'Invalid link'
    redirect_to root_path
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site_maps/new.html.slim
- if flash[:alert]
  h2 = flash[:alert]
= form_for :site_map, url: site_map_path, method: :post do |f|
  = f.label 'site'
  br
  = f.text_field :uri
  br
  = f.submit 'Create site map'

app/views/site_maps/show.html.slim
'You can download site map following the
= link_to 'link', @file_path